### ISSUE TITLE
Notice missing variable data

### ISSUE THREAD

**Issue by modellocate** [strangerstudios/pmpro-series#10]
I have the following notice:

This content is part of the [small blank button] series. You will gain access on day of your membership.

It does not have a number for "day" and there is no series name in the button. I think this is from a deleted series that did not delete cleanly. Where should I look in the database to clean it up and remove the link to the series?

Thanks!

**Comment by dparker1005** [comment]
We are very glad to hear that you were able to find a solution for this issue. I am going to close this issue as this question appears to be resolved.
