### ISSUE TITLE
Using alternative taxonomies

### ISSUE THREAD

**Issue by honestprep** [strangerstudios/pmpro-series#14]
Currently, PMPro Series only allows me to put Pages and Posts in my series. In my installation, my primary content belongs to a custom-made taxonomy. How do I use posts in this taxonomy under a given series?

**Comment by dparker1005** [comment]
You can allow series to contain post types other than posts and pages by using the `pmpros_post_types` filter:
https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L529

As this question is several years old, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
