### ISSUE TITLE
pmpro_getMemberDays() UTC vs local TZ issue?

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/pmpro-series#19]
Been debugging a problem in my Series(like) plugin where I have a member with a $wpdb->pmpro_memberships_users.startdate - '2014-02-03 13:00:00'.
When running pmpro_getMemberDays() for that user at 16:30:00 (cron job), the value returned is a float (184.927500). 

From my perspective (possibly incorrect, I admit), once the day-count is >184.0, we're technically on day 185. and as a result, the calculation in paid-memberships-pro/includes/function.php, on line 1530 is incorrect. At present, it reads as;

`
             $days = ($now - $startdate)/3600/24;
`

But it would be more "correct" (I think) to have it defined as;

`
            $days = round(abs($now - startdate) / (60*60*24));
`
In my limited testing, this will (always?) result in the correct day being returned.

**Comment by dparker1005** [comment]
You can customize exactly how long it will take for posts to become available by using the `pmpro_member_startdate` filter. I have just put together a code recipe that demonstrates a couple of strategies for changing when posts will unlock, including how to change the unlock time:
https://gist.github.com/dparker1005/d88e422c576587c473c9bb42b1bb8817

I have also added a commit to ensure that the timezone set in SQL/on the server does not affect the startdate timestamp retrieved by PMPro: https://github.com/strangerstudios/pmpro-series/commit/4adf08aea5a004b3311a58b6b3c41e6979cfe4ba
