### ISSUE TITLE
Disable series notification emails

### ISSUE THREAD

**Issue by dryan1144** [strangerstudios/pmpro-series#21]
Can you recommend the safest way to disable the Series notification emails? Long story but I'm looking to setup an auto-responder to take care of this for a client instead.

I see the sendEmail() function in class/esclass.pmproseries.php but I'm not sure how to remove this in an update-safe manner. 

(Also, maybe I missed it there but it would be great to include the option to remove these Series emails in your Disable all Emails plugin: https://gist.github.com/strangerstudios/3667545)

**Comment by camjshep** [comment]
Hi dryan1144, did you get a resolve to this? I'm also looking to have these notification emails disabled. Thanks.

**Comment by dparker1005** [comment]
We have a code recipe here which will disable the `new_content` email:
https://gist.github.com/kimcoleman/a8ecf99811397aa76cf0acb9caa06a98

As this question is several years old, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
