### ISSUE TITLE
Custom post types

### ISSUE THREAD

**Issue by agrolsy** [strangerstudios/pmpro-series#23]
Is it possible to add support for custom post types? Instead of just being able to select posts and pages f ex being able to select a WP Courseware course unit? (without having to create a post/page that shows just that unit)

**Comment by mdriess** [comment]
I also need a solution for this.

**Comment by positivejam** [comment]
To anyone who might have come across this thread: you can add PMPro Series support for your custom post types by putting the following code in your functions.php file:
```php
function add_cpt_to_pmpro_series($postTypes) {
  // Repeat the following line for other post types as necessary
  $postTypes[] = 'nameOfPostTypeGoesHere';
  return $postTypes;
}
add_filter('pmpros_post_types', 'add_cpt_to_pmpro_series');
```

**Comment by dparker1005** [comment]
Closing as this question has been answered by @positivejam.
