### ISSUE TITLE
Drip feed based on date instead of day delay

### ISSUE THREAD

**Issue by agrolsy** [strangerstudios/pmpro-series#24]
It would be great to be able to set a date when content should be accessible instead of a day delay, f ex post one available on October 5th, post two on October 10th etc, no matter when the user signs up (if the user signs up after that date, he will get access to all the posts)

**Comment by dparker1005** [comment]
I have just put together a code recipe that demonstrates a couple of strategies for customizing when posts will unlock by using the `pmpro_member_startdate` filter, including how to cause them to unlock on a specific day:
https://gist.github.com/dparker1005/d88e422c576587c473c9bb42b1bb8817

If you have further questions about this, please feel free to [open a new ticket in the PMPro support forum](https://www.paidmembershipspro.com/new-topic/)and we would be happy to go into more detail there.
