### ISSUE TITLE
New Filter Request: edit post type archive slug.

### ISSUE THREAD

**Issue by adaptifyDesigns** [strangerstudios/pmpro-series#29]
Hi, I love the `my_pmpros_series_labels` and `my_pmpros_series_registration` filters, referenced in [this gist](https://gist.github.com/strangerstudios/4fc33f3ee209b9dca00f/). But I would also like to edit the 'series' post type archive slug. 

Would you consider adding a new filter that would allow us to set the archive slug?

I used the above mentioned filters to change my Series post type to `programs`, and the slug base was successfully updated, so I can access the individual programs pages at `mysite.com/programs/program-name`, but I get a 404 when I try to access `mysite.com/programs`. The archive/feed page is still accessible at `mysite.com/series` though.

Also, is there a way to change the admin labels for the series post type, so it actually says "Programs" in the admin, instead of "Series"?

Is there a way I could just re-declare the `regestir_post_type()` function in my child theme and override the pmpro series function?

This is what I have in my child theme's `functions.php`:

```
function my_pmpros_series_labels($labels) { 
    $labels['slug'] = 'programs';
    return $labels;
}
add_filter('pmpros_series_labels', 'my_pmpros_series_labels');

function my_pmpros_series_registration($post_type) {
    $post_type['rewrite']['slug'] = 'programs';
    return $post_type;
}
add_filter('pmpros_series_registration', 'my_pmpros_series_registration');
```

Thanks in advance for any help you can provide. Your addon plugin is MUCH APPRECIATED!
- Colin

**Comment by dparker1005** [comment]
Both of these changes should be achievable using the existed filters.

Changing the slug used in the URL would require setting the `$post_type['has_archive']` element in the `pmpros_series_registration` filter:
https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L324

And changing the wording used in the admin menus would require setting the various elements in the array filtered by `pmpros_series_labels`:
https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L288-L300

As this behavior is already possible we are going to close this issue.If you have further questions about how to make these changes, please [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
