### ISSUE TITLE
Drip content based on Day of Week + Time stamp

### ISSUE THREAD

**Issue by loving1** [strangerstudios/pmpro-series#31]
Hi there! Is it possible to drip content so that every Monday other content is made available, not just # of days since purchase?  Also, time of day to drip content would be great. Is it possible with this?

Thanks so much!

**Comment by dparker1005** [comment]
I have just put together a code recipe that demonstrates a couple of strategies for customizing when posts will unlock by using the `pmpro_member_startdate` filter, including how to cause them to unlock on a specific day of the week and at a certain time:
https://gist.github.com/dparker1005/d88e422c576587c473c9bb42b1bb8817

If you have further questions about this, please feel free to [open a new ticket in the PMPro support forum](https://www.paidmembershipspro.com/new-topic/)and we would be happy to go into more detail there.
