### ISSUE TITLE
Support PHP 7.X

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-series#43]
When running code in PHP 7.X there's a warning:

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; PMProSeries has a deprecated constructor in /app/public/wp-content/plugins/pmpro-series/classes/class.pmproseries.php on line 2

**Comment by andrewlimaza** [comment]
We still need to test this PHP 7 versions, another issue on some systems show a JS error pop-up when trying to add posts / pages to a series.

Trying to recreate this issue.

**Comment by greathmaster** [comment]
I have reproduce this error for PHP 7.2. When you attempt to add a post to a series you receive a fatal error:

`Fatal error: Uncaught Error: [] operator not supported for strings `

**Comment by andrewlimaza** [comment]
Weird, I don't get that error any more with dev version. I have this issue now -> https://github.com/strangerstudios/pmpro-series/issues/54

**Comment by dparker1005** [comment]
I could not replicate this issue anymore using PHP 7.2. Looking through previous PRs, this issue should have been resolved here: https://github.com/strangerstudios/pmpro-series/pull/46
