### ISSUE TITLE
Fatal error when trying to add posts to a series

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-series#44]
PHP 7.X

Whenever trying to add a post to a series, a pop up error appears and this error gets logged:

PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /app/public/wp-content/plugins/pmpro-series/classes/class.pmproseries.php:52

**Comment by andrewlimaza** [comment]
Tested on 7.2 to be exact.

**Comment by mdawart** [comment]
Same problem here

**Comment by dparker1005** [comment]
I could not replicate this issue anymore using PHP 7.2. Looking through previous PRs, this issue should have been resolved here: https://github.com/strangerstudios/pmpro-series/pull/46
