### ISSUE TITLE
Change wording "You are on day X of your membership" once entire Series is available

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-series#53]
Once a user has reached a point that all Series content is available, we should update the message "You are on day X of your membership" to "You have completed the series." or something to this effect. This field could be a customizable setting per-Series CPT.

<img width="781" alt="screen shot 2018-12-20 at 1 01 07 pm" src="https://user-images.githubusercontent.com/5312875/50302381-ec9eb280-0457-11e9-8b72-f135e1fa7e1e.png">

**Comment by ideadude** [comment]
We should add a filter around this string and pass the user, timestamp, number of days/etc https://github.com/strangerstudios/pmpro-series/blob/dev/pmpro-series.php#L114

Then we could have a gist to remove it or change the wording. To show "end of series" we would need to know the posts and dates for the series.
