### ISSUE TITLE
Functionality tweaks?

### ISSUE THREAD

**Issue by marvmckay** [strangerstudios/pmpro-series#6]
How might I change the series display so that it's descending rather than ascending?   If someone is in the 3rd month of their series, I would prefer for them to see the 3rd release first, followed by the 2nd and the 1st, so that it always provides the newest content first with the rest following as an archive.

Also, is there a way to disable the display of future series items, which currently show up with the message: "available on day 30" - ?  I don't want a subscriber to see upcoming features, each month's release is supposed to be a surprise.

**Comment by dparker1005** [comment]
Closing issue as this question has been answered.
