### ISSUE TITLE
Update Paragraph Tag That Shows How Many Days a User is in a Membership

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-series#67]
Customer requests to hide the verbiage of how many days a user is into their membership.

Currently, the verbiage is written in a  generic paragraph tag with no classes to target.

I recommend a PR that will add a class to this paragraph tag for easier targeting using CSS.

**Comment by dparker1005** [comment]
This can now be done by targeting `.pmpro_series_days_into_membership_text` using CSS.
