### ISSUE TITLE
Does not allow me to add posts

### ISSUE THREAD

**Issue by ethan517** [strangerstudios/pmpro-series#7]
When I create a new series, the plugin only allows me to add pages, but not posts... it says you can add both, but in the scroll down menu where you add the content and set the delays, only my pages are listed... how do  I fix this???

**Comment by dparker1005** [comment]
Selecting both pages and posts should be possible by default, but you can also modify which post types are selectable using the `pmpros_post_types` filter:
https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L529

We are currently cleaning up this GitHub repository. As this question is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
