### ISSUE TITLE
Req- Setting a specific time of the next day in the series.

### ISSUE THREAD

**Issue by emos321** [strangerstudios/pmpro-series#70]
It would be nice if it was possible to set a specific time to start the next day in the series. Currently, it looks like the new day starts after 24 hours from the moment you sign up. It is not very convenient because if access to new content is set to (Delay 1 day, 2, 3 etc.) then each access to new content will be only in the evening (after 24h) and not e.g. in the morning.

**Comment by dparker1005** [comment]
I have just put together a code recipe that demonstrates a couple of strategies for customizing when posts will unlock by using the `pmpro_member_startdate` filter, including how to cause them to unlock at a specific time:
https://gist.github.com/dparker1005/d88e422c576587c473c9bb42b1bb8817

If you have further questions about this, please feel free to [open a new ticket in the PMPro support forum](https://www.paidmembershipspro.com/new-topic/)and we would be happy to go into more detail there.
