### ISSUE TITLE
Language files require update

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-series#79]
Some text strings are not currently included in the language files, e.g `available on %s.`

https://github.com/strangerstudios/pmpro-series/blob/9c21f4cd480321f9c01f1eb11b954fd0c332e1db/classes/class.pmproseries.php#L443

**Comment by ipokkel** [comment]
Temporary workaround: https://gist.github.com/ipokkel/b6fb9eadd968fb0a15e60493acc3f946

**Comment by emos321** [comment]
temporary and still not changed and you just need to change to make it work properly on 
`printf( esc_html__( 'available on day %s', 'pmpro-series' ), $date );`
...

**Comment by dparker1005** [comment]
We are generating language files to be included in the next release of the PMPro Series Add On.
