### ISSUE TITLE
list shortcode?

### ISSUE THREAD

**Issue by DotDotJames** [strangerstudios/pmpro-series#9]
Is there a shortcode for the list? Would like to be able to list series at end of each post in series &/or on sidebar. Ideally the list would detect which element of series is currently shown & bold that list element & perhaps lighten the text of posts that aren't yet viewable, or simply show the same not available yet button.

**Comment by kimcoleman** [comment]
Added your comment to https://github.com/strangerstudios/pmpro-series/issues/85
