### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by nftVegas** [strangerstudios/pmpro-series#95]
So the plugin is reading the day when last activation was made but one of my customer forgot to pay and now he must wait 6 months to see some of the content because he activated and the plugin will read from last activation not from the first activation day. How to fix that one?

**Comment by andrewlimaza** [comment]
You may try this gist - https://eighty20results.com/custom-code/preserve-start-date-pmpro-membership/

This should keep the members (very first) start date when they renew their membership level.
